apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-web-app
  labels:
    app: shopping-cart-web-app
spec:
  selector:
    app: shopping-cart-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
